"""
Cross-module rule tests for Registry service.
"""
import pytest
import requests as req_lib
from tests.helpers.curl_builder import attach_curl


def _post(node, url, headers, body):
    r = req_lib.Request("POST", url, headers=headers, json=body)
    p = r.prepare()
    attach_curl(node, p)
    return req_lib.Session().send(p)


_VALID_DEFINITION = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {"name": {"type": "string"}},
    "required": ["name"],
}


# ---------------------------------------------------------------------------
# BR-CM-001: IDGen library generates all registryIds on create
# ---------------------------------------------------------------------------

class TestBR_CM_001_idgen_library_generates_registry_ids:
    """Created data record has a non-empty registryId."""

    def test_created_data_has_registry_id(self, request, base_url, auth_headers):
        resp = _post(request.node, f"{base_url}/schema/seed-schema/data", auth_headers,
                     {"data": {"name": "IDGen Test Entry"}})
        assert resp.status_code in (200, 201), f"Data create failed: {resp.text}"
        record = resp.json()
        assert record.get("registryId") or record.get("id"), \
            "registryId must be generated by IDGen library and present in response"


# ---------------------------------------------------------------------------
# BR-CM-003: Signature verify requires Vault to be configured
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# BR-CM-002: Vault required gates service startup
# ---------------------------------------------------------------------------

class TestBR_CM_002_vault_required_gates_service_startup:
    """
    If VAULT_REQUIRED=true and Vault is not configured, the service exits at startup.
    If we can reach the service, it started successfully with a valid Vault config
    (or VAULT_REQUIRED=false). The test verifies the service is reachable.
    """

    def test_service_is_reachable_indicating_successful_startup(
        self, request, base_url, auth_headers
    ):
        resp = req_lib.get(f"{base_url}/schema/seed-schema", headers=auth_headers)
        assert resp.status_code in (200, 404), \
            f"Service must be reachable (valid Vault config at startup or VAULT_REQUIRED=false), got {resp.status_code}"


class TestBR_CM_003_signature_verify_requires_vault:
    """_verify endpoint returns 501 when Vault is not configured."""

    def test_verify_without_vault_returns_501(self, request, base_url, auth_headers):
        resp = req_lib.get(f"{base_url}/_verify", headers=auth_headers,
                           params={"registryId": "any-id", "schemaCode": "seed-schema"})
        assert resp.status_code in (200, 404, 501), \
            f"_verify should return 200 (with vault), 404 (no record), or 501 (no vault), got {resp.status_code}"


# ---------------------------------------------------------------------------
# BR-CM-004: Validation webhook errors reject unless fail-open
# ---------------------------------------------------------------------------

class TestBR_CM_004_validation_webhook_errors_reject_unless_fail_open:
    """When VALIDATION_WEBHOOK_ENABLED=true and webhook fails, mutation is rejected unless FAIL_OPEN."""

    def test_data_create_succeeds_without_webhook(self, request, base_url, auth_headers):
        resp = _post(request.node, f"{base_url}/schema/seed-schema/data", auth_headers,
                     {"data": {"name": "Webhook Test"}})
        assert resp.status_code in (200, 201), \
            f"Data create must succeed when no webhook configured, got {resp.status_code}: {resp.text}"
