spring.datasource.url=jdbc:postgresql://localhost:5432/notify
spring.datasource.username=notify
spring.datasource.password=notify

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.baseline-on-migrate=true

notify.plugins.directory=../providers

logging.level.org.digit.notify=DEBUG
