"""
Cross-module rule tests for Individual service.
"""
import pytest
import requests as req_lib
from tests.helpers.curl_builder import attach_curl


def _post(node, url, headers, body):
    r = req_lib.Request("POST", url, headers=headers, json=body)
    p = r.prepare()
    attach_curl(node, p)
    return req_lib.Session().send(p)


# ---------------------------------------------------------------------------
# BR-CM-001: IDGen required for individualId generation
# ---------------------------------------------------------------------------

class TestBR_CM_001_idgen_required_for_individual_id_generation:
    """Created individual has a non-empty individualId generated by IDGen."""

    @pytest.fixture(autouse=True)
    def _skip_without_idgen_url(self, request):
        if not request.config.getoption("--idgen-url", default=None):
            pytest.skip("--idgen-url not provided; IDGen cross-module test skipped")

    def test_created_individual_has_individual_id(self, request, base_url, auth_headers):
        import uuid
        mobile = f"+91{uuid.uuid4().int % 10_000_000_000:010d}"
        resp = _post(request.node, f"{base_url}/individuals", auth_headers,
                     {"individual": {"givenName": "Test", "mobileNumber": mobile}})
        assert resp.status_code in (200, 201), f"Create failed: {resp.text}"
        ind = resp.json().get("individual") or resp.json()
        assert ind.get("individualId"), \
            "individualId must be generated by IDGen and present in response"


# ---------------------------------------------------------------------------
# BR-CM-003: PubSub events are fire-and-forget
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# BR-CM-002: Vault encryption fails hard when enabled
# ---------------------------------------------------------------------------

class TestBR_CM_002_vault_encryption_fails_hard_when_enabled:
    """
    When VAULT_ENABLED=true, mobileNumber and email are encrypted/decrypted via Vault.
    This is an infrastructure-level rule — observable only when Vault is intentionally
    unavailable. We test the contract: create succeeds when service is running normally,
    and document the expected 500 when Vault is unreachable.
    """

    def test_create_succeeds_when_vault_operational(self, request, base_url, auth_headers):
        mobile = _build_mobile()
        resp = _post(request.node, f"{base_url}/individuals", auth_headers,
                     {"individual": {"givenName": "VaultTest", "mobileNumber": mobile}})
        assert resp.status_code in (200, 201), \
            "Individual create must succeed when Vault is operational (or VAULT_ENABLED=false)"


def _build_mobile():
    import uuid
    return f"+91{uuid.uuid4().int % 10_000_000_000:010d}"


class TestBR_CM_003_pubsub_events_are_fire_and_forget:
    """Create succeeds regardless of PubSub availability."""

    def test_create_returns_success_independent_of_pubsub(
        self, request, base_url, auth_headers
    ):
        import uuid
        mobile = f"+91{uuid.uuid4().int % 10_000_000_000:010d}"
        resp = _post(request.node, f"{base_url}/individuals", auth_headers,
                     {"individual": {"givenName": "PubSubTest", "mobileNumber": mobile}})
        assert resp.status_code in (200, 201), \
            f"Create must succeed regardless of PubSub availability, got {resp.status_code}: {resp.text}"
